# Generated by Django 4.0.1 on 2022-01-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_name', models.CharField(max_length=35)),
                ('owner_name', models.CharField(max_length=35)),
                ('language_used', models.CharField(max_length=20)),
                ('open_source', models.BooleanField()),
                ('description', models.TextField()),
                ('site', models.URLField()),
            ],
        ),
    ]
