# Generated by Django 4.0.1 on 2022-01-17 10:42

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('botlist', '0002_rename_submissions_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='bot_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='invite_link',
            field=models.URLField(default=datetime.datetime(2022, 1, 17, 10, 42, 33, 465013, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
