# Generated by Django 4.0.1 on 2022-01-19 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botlist', '0003_submission_bot_id_submission_invite_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='open_source',
        ),
    ]
