# Generated by Django 4.0.1 on 2022-01-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botlist', '0004_remove_submission_open_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='submitted',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
