# Generated by Django 4.0.1 on 2022-01-19 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botlist', '0005_submission_submitted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='submitted',
            new_name='approved',
        ),
    ]
