# Generated by Django 4.0.1 on 2022-01-19 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botlist', '0006_rename_submitted_submission_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='site',
            field=models.URLField(blank=True),
        ),
    ]
