# Generated by Django 4.0.1 on 2022-01-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botlist', '0007_alter_submission_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='profile_url',
            field=models.URLField(blank=True),
        ),
    ]
